export enum NotificationType {
  CLIENT_REPORTING_DATE = 'CLIENT_REPORTING_DATE',
  REMAINING_PRICE_DATE = 'REMAINING_PRICE_DATE',
  TICKET_ASSIGNED = 'TICKET_ASSIGNED',
  CLIENT_REPORTING_DATE_7_DAYS_PASSED = 'CLIENT_REPORTING_DATE_7_DAYS_PASSED'
}
